spring.application.name=task-bff

usuario.url=http://localhost:8080
agendador-tarefas.url=http://localhost:8081
notificacao.url=http://localhost:8082
server.port=8083

cron.horario=0 0/5 * * * ?

usuario.email=admin@admin.com
usuario.senha=1234
